### ISSUE TITLE
Is there a version working with Angular 5?

### ISSUE THREAD

**Issue by AppCostumi** [mprahl/s2i-angular-httpd24#7]
Hi, as title says, we'd like to know if there's a version working with Angular 5. On Docker Hub I can see only latest tag which supports only Angular 6+ apps.
Thanks in advance.

**Comment by mprahl** [comment]
Hi @AppCostumi,
I used to have an Angular 2-5 branch, but I removed it a while ago.

I believe we just need to create a new branch and basically revert this commit on that branch:
https://github.com/mprahl/s2i-angular-httpd24/commit/c6b261ea8b6c4d237753f2ca774018272c2807d7

If you're still interested. I can take a stab at doing that.

**Comment by mprahl** [comment]
I'll close this due to inactivity.
